FROM alpine:latest
ARG VERSION 
ARG PRODUCT 

RUN  PRODUCT=vault VERSION=1.16.3 /bin/sh -c apk add --update --virtual .deps --no-cache gnupg && \
    wget -qO- https://www.hashicorp.com/.well-known/pgp-key.txt | gpg --import && \
    wget https://releases.hashicorp.com/${PRODUCT}/${VERSION}/${PRODUCT}_${VERSION}_SHA256SUMS.sig && \
    wget https://releases.hashicorp.com/${PRODUCT}/${VERSION}/${PRODUCT}_${VERSION}_SHA256SUMS &&  \
    cd /tmp && wget https://releases.hashicorp.com/${PRODUCT}/${VERSION}/${PRODUCT}_${VERSION}_linux_amd64.zip \
    cd /tmp && wget https://releases.hashicorp.com/${PRODUCT}/${VERSION}/${PRODUCT}_${VERSION}_linux_amd64.zip
    
ENTRYPOINT ["vault"]
CMD ["server" "-config" "/opt/vault/conf/vault.hcl"]