USE app

CREATE TABLE USER (
    USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    IS_ACTIVE BOOLEAN,
    ACCOUNT_TYPE VARCHAR(50)
);