services:
  vault:
    image: hashicorp/vault
    container_name: vault-container
    environment:
      VAULT_ADDR: "https://0.0.0.0:8200"
      VAULT_API_ADDR: "https://0.0.0.0:8200"
      VAULT_ADDRESS: "https://0.0.0.0:8200"
      VAULT_UI: true
    ports:
      - "8200:8200"
      - "8201:8201"
    restart: always
    volumes:
      - ./config:/vault/config/:rw
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config /vault/config/config.hcl
    networks:
      - shared

  mysql-dev:
    image: mysql
    restart: always
    container_name: mysql-container
    ports:
      - "3306:3306"
    volumes:
      - ./config:/docker-entrypoint-initdb.d/:rw
    environment:
      MYSQL_ROOT_PASSWORD: spring-root
    networks:
      - shared

networks:
  shared:
    name: groups-and-users
