/*
 * User and Group Administration API
 * API for managing users and groups
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ando5360.middleware.api;

import com.google.gson.annotations.SerializedName;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Group
 */
public class GroupTest {
    /**
     * Model tests for Group
     */
    @Test
    public void testGroup() {
        // TODO: test Group
    }

}
